### ISSUE TITLE
Exchange links

### ISSUE THREAD

**Issue by Wxh16144** [any1024/BLOG#1]
I'm back at your github. It's great.
Maybe you don't have time to update, but I still hope you can add my blog address;
site: [https://github.com/Overcase/BLOG/tree/master/docs/about](https://github.com/Overcase/BLOG/tree/master/docs/about)
myblog:[http://blog.wxhboy.cn](http://blog.wxhboy.cn)

**Comment by Overcase** [comment]
yeah. no problem . think you fork my project

**Comment by Overcase** [comment]
yeah. no problem . thank you fork my project

**Comment by Wxh16144** [comment]
outdated
